config/routes.rb
StaticCms::Application.routes.draw do
  devise_for :users

   root 'home#index'

   resources :static_pages do
    get 'images_list',:on=>:collection
   end
   resources :images do
   end

end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "100x100>", :tiny => "50x50>" }, :default_url => ""
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def login_filter
  	if user_signed_in?
  	else
  		redirect_to :root, :alert => "You must be logged in!"
  	end	
  end	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	before_filter :login_filter
	def index
		@images = Image.all		
		#render :nothing=>true,:layout=>true
	end

	def new
		@image = Image.new
	end	

	def create
		@image = Image.new(image_params)
		@image.save
		render :action => "list_image", :layout => true
	end
	
	def list_image
	end	

	private
	def image_params
		params.require(:image).permit(:title,:caption,:avatar)
	end	

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_filter :set_static_page,:only=>[:show,:edit,:update,:destroy]
	before_filter :login_filter

	def index
		@static_pages = StaticPage.all
	end

	def show
	end

	def new
		@static_page = StaticPage.new
	end

	def create
		@static_page = StaticPage.new static_page_params
		@static_page.save
		redirect_to @static_page
	end

	def edit
	end

	def update
	end

	def destroy
	end

	def images_list
		@images = Image.all
		render :layout=>false
	end

    private
	def static_page_params
		params.require(:static_page).permit(:title,:description)
	end

	def set_static_page
		@static_page = StaticPage.find params[:id]
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<%=image_tag "/assets/home.jpg"%>

app/views/images/index.html.erb
<%= "MEDIUM" %> <br>
<% @images.each do |image|%>
	<%= image_tag image.avatar.url(:medium) %>
<% end %> <br>
<%= "THUMB" %>	<br>
<% @images.each do |image|%>	
	<%= image_tag image.avatar.url(:thumb) %>
<% end %> <br>
<%= "TINY" %> <br>
<% @images.each do |image|%>	
	<%= image_tag image.avatar.url(:tiny)%>
<% end %>

app/views/images/list_image.html.erb
<%#= image_tag @image.avatar.url %>
<%= image_tag @image.avatar.url(:medium) %>
<%= image_tag @image.avatar.url(:thumb) %>
<%= image_tag @image.avatar.url(:tiny)%>

app/views/images/new.html.erb
<%= form_tag(@image,:multipart => true ) do %>
  <%= label_tag :title %>
  <%= text_field  "image","title" %>
  <%= label_tag :caption %>
  <%= text_field "image","caption" %>  
  <%= file_field "image","avatar" %>
  <%= submit_tag 'Upload' %>
<%end%>

<!-- 12bit018

15/05/95 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "StaticCms" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">StaticCms</a>
          <div class="container-fluid nav-collapse">
            <!-- <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul> -->
            <ul class="nav pull-right">
              <%if user_signed_in?%>
                <li><%=link_to "Home",root_url%></li>              
                <li><%=link_to "Logout",destroy_user_session_path,method: :delete%></li>
              <%else%>
                 <li><%=link_to "Login",new_user_session_path%></li>
              <%end%>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Menus</li>
              <li><%= link_to "StaticPage", static_pages_path  %></li>
              <li><%= link_to "Images", new_image_path  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; BrightShade 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/static_pages/_form.html.erb
<%=form_for @static_page do |f|%>
  <div class="form_element">
    <%=f.text_field :title%>
  </div>
  <div class="form_element default">
    <button class="prev"><<</button>
    <div class="gallery_box jCarouselLite">
      <ul class="image_box">
        <li>
           <%=image_tag "/assets/add_logo.jpeg",:class=>"add_gallery_image",:href=>images_list_static_pages_path%>
        </li>
        <li>
           <%=image_tag "/assets/add_logo.jpeg"%>
        </li>
      </ul>
      <div class="clear"></div>
    </div>
    <button class="next">>></button>
  </div>
  <div class="form_element">
    <%=f.text_area :description,:id=>"tiny_editor"%>
  </div>
  <%=f.submit "Make"%>
<!-- <textarea id="elm1" name="area"></textarea> -->
<%end%>
<script type="text/javascript">
  $(document).ready(function(){ 
    $(".default .jCarouselLite").jCarouselLite({
    btnNext: ".default .next",
    btnPrev: ".default .prev"
    });
  })
</script>
<script type="text/javascript">
  $(document).ready(function(){
    $(".add_gallery_image").colorbox({
      href:$(this).attr('href'),
      width:"1000px",
      height:"500px"
      });
  });
</script>
<script type="text/javascript">
tinymce.init({
    selector: "textarea#tiny_editor",
    theme: "modern",
    width: 700,
    height: 300,
    plugins: [
         "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
         "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
         "save table contextmenu directionality emoticons template paste textcolor"
   ],
   content_css: "css/content.css",
   toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | l      ink image | print preview media fullpage | forecolor backcolor emoticons", 
   style_formats: [
        {title: 'Bold text', inline: 'b'},
        {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
        {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
        {title: 'Example 1', inline: 'span', classes: 'example1'},
        {title: 'Example 2', inline: 'span', classes: 'example2'},
        {title: 'Table styles'},
        {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
    ]
 }); 
</script>

app/views/static_pages/images_list.html.erb
<%@images.each do |image|%>
  <%=image_tag image.avatar.url(:thumb)%>
<%end%>

app/views/static_pages/index.html.erb
<%@static_pages.each do |static_page|%>
  <%=link_to static_page.title,static_page_path(static_page)%><br/>
<%end%>
<%=link_to "New",new_static_page_path%>

app/views/static_pages/new.html.erb
<%=render :partial=>"form"%>